// Generates src/shared/version.ts from package.json + git.
//
// The version string is MAJOR.MINOR.PATCH-<buildhash>, e.g. 0.1.0-01f8e:
//   - MAJOR.MINOR.PATCH comes from package.json (bumped deliberately via
//     scripts/bump.mjs), and
//   - <buildhash> is the short git commit the build was cut from, with a
//     `-dirty` suffix when the working tree has uncommitted changes.
//
// Run automatically before dev / build / typecheck (see package.json scripts),
// so the generated file always reflects the exact commit in the binary. The
// file is git-ignored — it is a build product, never committed.
import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

function git(cmd, fallback) {
  try {
    return execSync(`git ${cmd}`, { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim()
  } catch {
    return fallback
  }
}

const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
const version = pkg.version
const hash = git('rev-parse --short=5 HEAD', 'nogit')
const dirty = git('status --porcelain', '') !== ''
const branch = git('rev-parse --abbrev-ref HEAD', 'unknown')
const buildTime = new Date().toISOString()
const full = `${version}-${hash}${dirty ? '-dirty' : ''}`

const contents = `// GENERATED by scripts/gen-version.mjs — do not edit, do not commit.
// Regenerated before every dev / build / typecheck run.
export const APP_VERSION = '${version}'
export const BUILD_HASH = '${hash}'
export const BUILD_DIRTY = ${dirty}
export const BUILD_BRANCH = '${branch}'
export const BUILD_TIME = '${buildTime}'
export const FULL_VERSION = '${full}'
`

const dest = join(root, 'src', 'shared')
mkdirSync(dest, { recursive: true })
writeFileSync(join(dest, 'version.ts'), contents)
console.log(`[gen-version] ${full} (${branch}) built ${buildTime}`)
